// <auto-generated />
using System;
using Longhl104.ShelterHub;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Longhl104.ShelterHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250803021430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shelter_hub")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PetId"));

                    b.Property<int?>("BreedId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsGoodWithKids")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGoodWithPets")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShelterId")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("PetId");

                    b.HasIndex("BreedId");

                    b.HasIndex("ShelterId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "SpeciesId", "BreedId");

                    b.ToTable("pets", "shelter_hub");
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.PetBreed", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BreedId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("BreedId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("pet_breeds", "shelter_hub");

                    b.HasData(
                        new
                        {
                            BreedId = 1,
                            Name = "Mixed Breed",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 2,
                            Name = "Labrador Retriever",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 3,
                            Name = "Golden Retriever",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 4,
                            Name = "German Shepherd",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 5,
                            Name = "French Bulldog",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 6,
                            Name = "Bulldog",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 7,
                            Name = "Poodle",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 8,
                            Name = "Beagle",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 9,
                            Name = "Rottweiler",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 10,
                            Name = "Yorkshire Terrier",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 11,
                            Name = "Chihuahua",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 12,
                            Name = "Border Collie",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 13,
                            Name = "Australian Shepherd",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 14,
                            Name = "Siberian Husky",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 15,
                            Name = "Boxer",
                            SpeciesId = 1
                        },
                        new
                        {
                            BreedId = 16,
                            Name = "Domestic Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 17,
                            Name = "Domestic Longhair",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 18,
                            Name = "Persian",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 19,
                            Name = "Maine Coon",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 20,
                            Name = "Ragdoll",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 21,
                            Name = "British Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 22,
                            Name = "Siamese",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 23,
                            Name = "American Shorthair",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 24,
                            Name = "Russian Blue",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 25,
                            Name = "Bengal",
                            SpeciesId = 2
                        },
                        new
                        {
                            BreedId = 26,
                            Name = "Mixed Breed",
                            SpeciesId = 3
                        },
                        new
                        {
                            BreedId = 27,
                            Name = "Holland Lop",
                            SpeciesId = 3
                        },
                        new
                        {
                            BreedId = 28,
                            Name = "Netherland Dwarf",
                            SpeciesId = 3
                        },
                        new
                        {
                            BreedId = 29,
                            Name = "Mini Rex",
                            SpeciesId = 3
                        },
                        new
                        {
                            BreedId = 30,
                            Name = "Lionhead",
                            SpeciesId = 3
                        },
                        new
                        {
                            BreedId = 31,
                            Name = "Budgerigar",
                            SpeciesId = 4
                        },
                        new
                        {
                            BreedId = 32,
                            Name = "Cockatiel",
                            SpeciesId = 4
                        },
                        new
                        {
                            BreedId = 33,
                            Name = "Canary",
                            SpeciesId = 4
                        },
                        new
                        {
                            BreedId = 34,
                            Name = "Lovebird",
                            SpeciesId = 4
                        },
                        new
                        {
                            BreedId = 35,
                            Name = "Conure",
                            SpeciesId = 4
                        },
                        new
                        {
                            BreedId = 36,
                            Name = "American Guinea Pig",
                            SpeciesId = 5
                        },
                        new
                        {
                            BreedId = 37,
                            Name = "Peruvian Guinea Pig",
                            SpeciesId = 5
                        },
                        new
                        {
                            BreedId = 38,
                            Name = "Abyssinian Guinea Pig",
                            SpeciesId = 5
                        },
                        new
                        {
                            BreedId = 39,
                            Name = "Syrian Hamster",
                            SpeciesId = 6
                        },
                        new
                        {
                            BreedId = 40,
                            Name = "Dwarf Hamster",
                            SpeciesId = 6
                        },
                        new
                        {
                            BreedId = 41,
                            Name = "Domestic Ferret",
                            SpeciesId = 7
                        });
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.PetSpecies", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SpeciesId");

                    b.ToTable("pet_species", "shelter_hub");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            SpeciesId = 2,
                            Name = "Cat"
                        },
                        new
                        {
                            SpeciesId = 3,
                            Name = "Rabbit"
                        },
                        new
                        {
                            SpeciesId = 4,
                            Name = "Bird"
                        },
                        new
                        {
                            SpeciesId = 5,
                            Name = "Guinea Pig"
                        },
                        new
                        {
                            SpeciesId = 6,
                            Name = "Hamster"
                        },
                        new
                        {
                            SpeciesId = 7,
                            Name = "Ferret"
                        },
                        new
                        {
                            SpeciesId = 8,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.Shelter", b =>
                {
                    b.Property<int>("ShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShelterId"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ShelterAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShelterContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ShelterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ShelterId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("shelters", "shelter_hub");
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.Pet", b =>
                {
                    b.HasOne("Longhl104.ShelterHub.Models.PostgreSql.PetBreed", "Breed")
                        .WithMany("Pets")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Longhl104.ShelterHub.Models.PostgreSql.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Longhl104.ShelterHub.Models.PostgreSql.PetSpecies", "Species")
                        .WithMany("Pets")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Shelter");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.PetBreed", b =>
                {
                    b.HasOne("Longhl104.ShelterHub.Models.PostgreSql.PetSpecies", "Species")
                        .WithMany("Breeds")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.PetBreed", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.PetSpecies", b =>
                {
                    b.Navigation("Breeds");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
