using System;
using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Longhl104.ShelterHub.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "shelter_hub");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:postgis", ",,");

            migrationBuilder.CreateTable(
                name: "pet_species",
                schema: "shelter_hub",
                columns: table => new
                {
                    SpeciesId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_pet_species", x => x.SpeciesId);
                });

            migrationBuilder.CreateTable(
                name: "shelters",
                schema: "shelter_hub",
                columns: table => new
                {
                    ShelterId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    ShelterName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    ShelterContactNumber = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    ShelterAddress = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Location = table.Column<Point>(type: "geometry (point, 4326)", nullable: true),
                    Latitude = table.Column<double>(type: "double precision", nullable: true),
                    Longitude = table.Column<double>(type: "double precision", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_shelters", x => x.ShelterId);
                });

            migrationBuilder.CreateTable(
                name: "pet_breeds",
                schema: "shelter_hub",
                columns: table => new
                {
                    BreedId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    SpeciesId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_pet_breeds", x => x.BreedId);
                    table.ForeignKey(
                        name: "FK_pet_breeds_pet_species_SpeciesId",
                        column: x => x.SpeciesId,
                        principalSchema: "shelter_hub",
                        principalTable: "pet_species",
                        principalColumn: "SpeciesId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "pets",
                schema: "shelter_hub",
                columns: table => new
                {
                    PetId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    SpeciesId = table.Column<int>(type: "integer", nullable: false),
                    BreedId = table.Column<int>(type: "integer", nullable: true),
                    ShelterId = table.Column<int>(type: "integer", nullable: false),
                    Gender = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    DateOfBirth = table.Column<DateOnly>(type: "date", nullable: true),
                    Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    AdoptionFee = table.Column<decimal>(type: "numeric", nullable: false),
                    IsSpayedNeutered = table.Column<bool>(type: "boolean", nullable: false),
                    IsVaccinated = table.Column<bool>(type: "boolean", nullable: false),
                    IsGoodWithKids = table.Column<bool>(type: "boolean", nullable: false),
                    IsGoodWithPets = table.Column<bool>(type: "boolean", nullable: false),
                    IsHouseTrained = table.Column<bool>(type: "boolean", nullable: false),
                    Status = table.Column<int>(type: "integer", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    MainImageFileExtension = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_pets", x => x.PetId);
                    table.ForeignKey(
                        name: "FK_pets_pet_breeds_BreedId",
                        column: x => x.BreedId,
                        principalSchema: "shelter_hub",
                        principalTable: "pet_breeds",
                        principalColumn: "BreedId",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_pets_pet_species_SpeciesId",
                        column: x => x.SpeciesId,
                        principalSchema: "shelter_hub",
                        principalTable: "pet_species",
                        principalColumn: "SpeciesId",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_pets_shelters_ShelterId",
                        column: x => x.ShelterId,
                        principalSchema: "shelter_hub",
                        principalTable: "shelters",
                        principalColumn: "ShelterId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                schema: "shelter_hub",
                table: "pet_species",
                columns: new[] { "SpeciesId", "Name" },
                values: new object[,]
                {
                    { 1, "Dog" },
                    { 2, "Cat" },
                    { 3, "Rabbit" },
                    { 4, "Bird" },
                    { 5, "Guinea Pig" },
                    { 6, "Hamster" },
                    { 7, "Ferret" },
                    { 8, "Other" }
                });

            migrationBuilder.InsertData(
                schema: "shelter_hub",
                table: "pet_breeds",
                columns: new[] { "BreedId", "Name", "SpeciesId" },
                values: new object[,]
                {
                    { 1, "Mixed Breed", 1 },
                    { 2, "Affenpinscher", 1 },
                    { 3, "Afghan Hound", 1 },
                    { 4, "Airedale Terrier", 1 },
                    { 5, "Akita", 1 },
                    { 6, "Akita (Japanese)", 1 },
                    { 7, "Alaskan Malamute", 1 },
                    { 8, "American Hairless Terrier", 1 },
                    { 9, "American Staffordshire Terrier", 1 },
                    { 10, "Anatolian Shepherd Dog", 1 },
                    { 11, "Australasian Bosdog ", 1 },
                    { 12, "Australian Cattle Dog", 1 },
                    { 13, "Australian Kelpie", 1 },
                    { 14, "Australian Shepherd", 1 },
                    { 15, "Australian Silky Terrier", 1 },
                    { 16, "Australian Stumpy Tail Cattle Dog", 1 },
                    { 17, "Australian Terrier", 1 },
                    { 18, "Azawakh", 1 },
                    { 19, "Basenji", 1 },
                    { 20, "Basset Fauve de Bretagne", 1 },
                    { 21, "Basset Hound", 1 },
                    { 22, "Beagle", 1 },
                    { 23, "Bearded Collie", 1 },
                    { 24, "Beauceron (Berger de Beauce)", 1 },
                    { 25, "Bedlington Terrier", 1 },
                    { 26, "Belgian Shepherd Dog (Groenendael)", 1 },
                    { 27, "Belgian Shepherd Dog (Laekenois)", 1 },
                    { 28, "Belgian Shepherd Dog (Malinois)", 1 },
                    { 29, "Belgian Shepherd Dog (Tervueren)", 1 },
                    { 30, "Bergamasco Shepherd Dog", 1 },
                    { 31, "Bernese Mountain Dog", 1 },
                    { 32, "Bichon Frise", 1 },
                    { 33, "Black and Tan Coonhound", 1 },
                    { 34, "Bloodhound", 1 },
                    { 35, "Bluetick Coonhound", 1 },
                    { 36, "Bolognese", 1 },
                    { 37, "Border Collie", 1 },
                    { 38, "Border Terrier", 1 },
                    { 39, "Borzoi", 1 },
                    { 40, "Boston Terrier ", 1 },
                    { 41, "Bouvier des Flandres", 1 },
                    { 42, "Boxer", 1 },
                    { 43, "Bracco Italiano", 1 },
                    { 44, "Briard", 1 },
                    { 45, "British Bulldog", 1 },
                    { 46, "Brittany", 1 },
                    { 47, "Bull Terrier", 1 },
                    { 48, "Bull Terrier (Miniature)", 1 },
                    { 49, "Bullmastiff", 1 },
                    { 50, "Cairn Terrier", 1 },
                    { 51, "Canaan Dog", 1 },
                    { 52, "Canadian Eskimo Dog", 1 },
                    { 53, "Cane Corso", 1 },
                    { 54, "Caucasian Shepherd Dog", 1 },
                    { 55, "Cavalier King Charles Spaniel", 1 },
                    { 56, "Central Asian Shepherd Dog", 1 },
                    { 57, "Cesky Terrier", 1 },
                    { 58, "Chesapeake Bay Retriever", 1 },
                    { 59, "Chihuahua (Long Coat)", 1 },
                    { 60, "Chihuahua (Smooth Coat)", 1 },
                    { 61, "Chinese Crested Dog", 1 },
                    { 62, "Chow Chow", 1 },
                    { 63, "Chow Chow (Smooth)", 1 },
                    { 64, "Cirneco Dell 'Etna", 1 },
                    { 65, "Clumber Spaniel", 1 },
                    { 66, "Cocker Spaniel", 1 },
                    { 67, "Cocker Spaniel (American)", 1 },
                    { 68, "Collie (Rough)", 1 },
                    { 69, "Collie (Smooth)", 1 },
                    { 70, "Coton De Tulear", 1 },
                    { 71, "Curly Coated Retriever", 1 },
                    { 72, "Dachshund Kaninchen Long Haired", 1 },
                    { 73, "Dachshund Kaninchen Smooth Haired", 1 },
                    { 74, "Dachshund Kaninchen Wire Haired", 1 },
                    { 75, "Dachshund Long Haired & Miniature Long Haired", 1 },
                    { 76, "Dachshund Smooth Haired & Miniature Smooth Haired", 1 },
                    { 77, "Dachshund Wire Haired & Miniature Wire Haired", 1 },
                    { 78, "Dalmatian", 1 },
                    { 79, "Dandie Dinmont Terrier", 1 },
                    { 80, "Deerhound", 1 },
                    { 81, "Dobermann", 1 },
                    { 82, "Dogue de Bordeaux", 1 },
                    { 83, "Dutch Shepherd", 1 },
                    { 84, "English Setter", 1 },
                    { 85, "English Springer Spaniel", 1 },
                    { 86, "English Toy Terrier (Black & Tan)", 1 },
                    { 87, "Estrela Mountain Dog", 1 },
                    { 88, "Eurasier", 1 },
                    { 89, "Field Spaniel", 1 },
                    { 90, "Finnish Lapphund", 1 },
                    { 91, "Finnish Spitz", 1 },
                    { 92, "Flat Coated Retriever", 1 },
                    { 93, "Fox Terrier (Smooth)", 1 },
                    { 94, "Fox Terrier (Wire)", 1 },
                    { 95, "Foxhound", 1 },
                    { 96, "French Bulldog", 1 },
                    { 97, "German Hunting Terrier", 1 },
                    { 98, "German Pinscher", 1 },
                    { 99, "German Shepherd Dog", 1 },
                    { 100, "German Shepherd Dog (Long Stock Coat)", 1 },
                    { 101, "German Shorthaired Pointer", 1 },
                    { 102, "German Spitz - (Klein) (Mittel)", 1 },
                    { 103, "German Wirehaired Pointer", 1 },
                    { 104, "Glen of Imaal Terrier", 1 },
                    { 105, "Golden Retriever", 1 },
                    { 106, "Gordon Setter", 1 },
                    { 107, "Grand Basset Griffon Vendeen", 1 },
                    { 108, "Great Dane", 1 },
                    { 109, "Greyhound", 1 },
                    { 110, "Griffon Bruxellois (Smooth)", 1 },
                    { 111, "Griffon Bruxellois (Wire)", 1 },
                    { 112, "Hamiltonstovare", 1 },
                    { 113, "Harrier", 1 },
                    { 114, "Havanese", 1 },
                    { 115, "Hungarian Vizsla", 1 },
                    { 116, "Hungarian Wirehaired Vizsla", 1 },
                    { 117, "Ibizan Hound", 1 },
                    { 118, "Icelandic Sheepdog", 1 },
                    { 119, "Irish Red and White Setter ", 1 },
                    { 120, "Irish Setter", 1 },
                    { 121, "Irish Terrier", 1 },
                    { 122, "Irish Water Spaniel", 1 },
                    { 123, "Irish Wolfhound", 1 },
                    { 124, "Italian Greyhound", 1 },
                    { 125, "Italian Spinone", 1 },
                    { 126, "Jack Russell Terrier", 1 },
                    { 127, "Japanese Chin", 1 },
                    { 128, "Japanese Spitz", 1 },
                    { 129, "Kangal Shepherd Dog", 1 },
                    { 130, "Karelian Bear Dog", 1 },
                    { 131, "Keeshond", 1 },
                    { 132, "Kerry Blue Terrier", 1 },
                    { 133, "King Charles Spaniel", 1 },
                    { 134, "Komondor", 1 },
                    { 135, "Kuvasz", 1 },
                    { 136, "Labrador Retriever", 1 },
                    { 137, "Lagotto Romagnolo", 1 },
                    { 138, "Lakeland Terrier", 1 },
                    { 139, "Landseer (European Continental Type)", 1 },
                    { 140, "Large Munsterlander", 1 },
                    { 141, "Leonberger", 1 },
                    { 142, "Lhasa Apso", 1 },
                    { 143, "Lowchen (Little Lion Dog)", 1 },
                    { 144, "Maltese", 1 },
                    { 145, "Manchester Terrier", 1 },
                    { 146, "Maremma Sheepdog", 1 },
                    { 147, "Mastiff", 1 },
                    { 148, "Miniature Pinscher", 1 },
                    { 149, "Murray River Retriever", 1 },
                    { 150, "Neapolitan Mastiff", 1 },
                    { 151, "Newfoundland", 1 },
                    { 152, "Norfolk Terrier", 1 },
                    { 153, "Norwegian Buhund", 1 },
                    { 154, "Norwegian Elkhound", 1 },
                    { 155, "Norwich Terrier ", 1 },
                    { 156, "Nova Scotia Duck Tolling Retriever", 1 },
                    { 157, "Old English Sheepdog", 1 },
                    { 158, "Otterhound", 1 },
                    { 159, "Papillon", 1 },
                    { 160, "Parson Russell Terrier", 1 },
                    { 161, "Pekingese", 1 },
                    { 162, "Peruvian Hairless Dog (Small, Medium, Large)", 1 },
                    { 163, "Petit Basset Griffon Vendeen ", 1 },
                    { 164, "Pharaoh Hound", 1 },
                    { 165, "Pointer", 1 },
                    { 166, "Polish Lowland Sheepdog", 1 },
                    { 167, "Pomeranian", 1 },
                    { 168, "Poodle (Miniature)", 1 },
                    { 169, "Poodle (Standard)", 1 },
                    { 170, "Poodle (Toy)", 1 },
                    { 171, "Porcelaine", 1 },
                    { 172, "Portuguese Podengo ", 1 },
                    { 173, "Portuguese Podengo (Large)", 1 },
                    { 174, "Portuguese Podengo (Medium)", 1 },
                    { 175, "Portuguese Podengo (Small)", 1 },
                    { 176, "Portuguese Water Dog", 1 },
                    { 177, "Prague Ratter", 1 },
                    { 178, "Pug", 1 },
                    { 179, "Puli", 1 },
                    { 180, "Pumi", 1 },
                    { 181, "Pyrenean Mastiff", 1 },
                    { 182, "Pyrenean Mountain Dog", 1 },
                    { 183, "Pyrenean Sheepdog Longhaired", 1 },
                    { 184, "Rhodesian Ridgeback", 1 },
                    { 185, "Rottweiler", 1 },
                    { 186, "Russian Black Terrier", 1 },
                    { 187, "Russian Toy (Long Haired)", 1 },
                    { 188, "Russian Toy (Smooth Haired)", 1 },
                    { 189, "Saluki", 1 },
                    { 190, "Samoyed", 1 },
                    { 191, "Schipperke", 1 },
                    { 192, "Schnauzer ", 1 },
                    { 193, "Schnauzer (Giant)", 1 },
                    { 194, "Schnauzer (Miniature)", 1 },
                    { 195, "Scottish Terrier", 1 },
                    { 196, "Sealyham Terrier", 1 },
                    { 197, "Shar Pei", 1 },
                    { 198, "Shetland Sheepdog", 1 },
                    { 199, "Shiba Inu", 1 },
                    { 200, "Shih Tzu", 1 },
                    { 201, "Siberian Husky", 1 },
                    { 202, "Skye Terrier", 1 },
                    { 203, "Sloughi", 1 },
                    { 204, "Soft Coated Wheaten Terrier", 1 },
                    { 205, "Spanish Mastiff", 1 },
                    { 206, "Spanish Water Dog", 1 },
                    { 207, "St Bernard", 1 },
                    { 208, "Staffordshire Bull Terrier", 1 },
                    { 209, "Sussex Spaniel", 1 },
                    { 210, "Swedish Lapphund", 1 },
                    { 211, "Swedish Vallhund", 1 },
                    { 212, "Tatra Shepherd Dog", 1 },
                    { 213, "Tenterfield Terrier", 1 },
                    { 214, "Tibetan Mastiff", 1 },
                    { 215, "Tibetan Spaniel", 1 },
                    { 216, "Tibetan Terrier", 1 },
                    { 217, "Tornjak", 1 },
                    { 218, "Weimaraner", 1 },
                    { 219, "Weimaraner (Long Hair)", 1 },
                    { 220, "Welsh Corgi (Cardigan)", 1 },
                    { 221, "Welsh Corgi (Pembroke)", 1 },
                    { 222, "Welsh Springer Spaniel", 1 },
                    { 223, "Welsh Terrier", 1 },
                    { 224, "West Highland White Terrier", 1 },
                    { 225, "Whippet", 1 },
                    { 226, "White Swiss Shepherd Dog", 1 },
                    { 227, "Wirehaired Slovakian Pointer", 1 },
                    { 228, "Xoloitzcuintle - (Miniature) (Intermediate) (Standard) ", 1 },
                    { 229, "Yakutian Laika", 1 },
                    { 230, "Yorkshire Terrier", 1 },
                    { 231, "Other", 1 },
                    { 232, "Domestic Shorthair", 2 },
                    { 233, "Domestic Longhair", 2 },
                    { 234, "American Bobtail", 2 },
                    { 235, "Australian Mist", 2 },
                    { 236, "Balinese-Javanese Cat", 2 },
                    { 237, "Bengal", 2 },
                    { 238, "Birman", 2 },
                    { 239, "Bombay", 2 },
                    { 240, "British Shorthair", 2 },
                    { 241, "Burmese", 2 },
                    { 242, "Burmilla", 2 },
                    { 243, "Cornish Rex", 2 },
                    { 244, "Devon Rex", 2 },
                    { 245, "Egyptian Mau", 2 },
                    { 246, "Exotic Shorthair", 2 },
                    { 247, "Himalayan Cat", 2 },
                    { 248, "Japanese Bobtail", 2 },
                    { 249, "Korat", 2 },
                    { 250, "LaPerm", 2 },
                    { 251, "Maine Coon", 2 },
                    { 252, "Manx Cat", 2 },
                    { 253, "Norwegian Forest Cat", 2 },
                    { 254, "Ocicat", 2 },
                    { 255, "Oriental", 2 },
                    { 256, "Persian", 2 },
                    { 257, "Ragdoll", 2 },
                    { 258, "Russian Blue", 2 },
                    { 259, "Scottish Fold", 2 },
                    { 260, "Selkirk Rex", 2 },
                    { 261, "Siamese", 2 },
                    { 262, "Siberian Forest Cat", 2 },
                    { 263, "Singapura", 2 },
                    { 264, "Snowshoe", 2 },
                    { 265, "Somali", 2 },
                    { 266, "Sphynx Cat", 2 },
                    { 267, "Tiffanie", 2 },
                    { 268, "Tonkinese", 2 },
                    { 269, "Turkish Angora", 2 },
                    { 270, "Turkish Van", 2 },
                    { 271, "Other", 2 },
                    { 272, "Mixed Breed", 3 },
                    { 273, "Alaskan", 3 },
                    { 274, "Altex", 3 },
                    { 275, "American", 3 },
                    { 276, "American Chinchilla [US]", 3 },
                    { 277, "American Fuzzy Lop", 3 },
                    { 278, "American Sable", 3 },
                    { 279, "Angora", 3 },
                    { 280, "Argente Bleu", 3 },
                    { 281, "Argente Brun [UK]", 3 },
                    { 282, "Argente Brun [US]", 3 },
                    { 283, "Argente Clair", 3 },
                    { 284, "Argente Crème [UK]", 3 },
                    { 285, "Argente de Champagne [UK]", 3 },
                    { 286, "Argente Noir", 3 },
                    { 287, "Argente St Hubert", 3 },
                    { 288, "Armenian Marder", 3 },
                    { 289, "Astrex", 3 },
                    { 290, "Aurora Negro", 3 },
                    { 291, "Baladi Black", 3 },
                    { 292, "Baladi Red", 3 },
                    { 293, "Baladi White", 3 },
                    { 294, "Bauscat", 3 },
                    { 295, "Beige [UK]", 3 },
                    { 296, "Belgian Hare [UK]", 3 },
                    { 297, "Belgian Hare [US]", 3 },
                    { 298, "Beveren [UK]", 3 },
                    { 299, "Beveren [US]", 3 },
                    { 300, "Blanc de Bouscat", 3 },
                    { 301, "Blanc de Hotot", 3 },
                    { 302, "Blanc de Popielno", 3 },
                    { 303, "Blanc de Termonde", 3 },
                    { 304, "Blue of Ham", 3 },
                    { 305, "Blue of Sint-Niklaas", 3 },
                    { 306, "Bourbonnais Grey", 3 },
                    { 307, "Brazilian", 3 },
                    { 308, "Britannia Petite [US]", 3 },
                    { 309, "British Giant", 3 },
                    { 310, "Brown Chestnut of Lorraine", 3 },
                    { 311, "Caldes", 3 },
                    { 312, "Californian [UK]", 3 },
                    { 313, "Californian [US]", 3 },
                    { 314, "Canadian Plush Lop", 3 },
                    { 315, "Carmagnola Grey", 3 },
                    { 316, "Cashmere Lop", 3 },
                    { 317, "Champagne d'Argent [US]", 3 },
                    { 318, "Chaudry", 3 },
                    { 319, "Checkered Giant [US]", 3 },
                    { 320, "Chinchilla [UK]", 3 },
                    { 321, "Chinchilla Giganta [UK]", 3 },
                    { 322, "Cinnamon", 3 },
                    { 323, "Continental Giant Coloured", 3 },
                    { 324, "Continental Giant White", 3 },
                    { 325, "Creme d'Argent [US]", 3 },
                    { 326, "Cuban Brown", 3 },
                    { 327, "Czech Red", 3 },
                    { 328, "Czech Solver [CZ]", 3 },
                    { 329, "Czech Spot", 3 },
                    { 330, "Czech White", 3 },
                    { 331, "Dalmatian", 3 },
                    { 332, "Deilenaar", 3 },
                    { 333, "Dutch [UK]", 3 },
                    { 334, "Dutch [US]", 3 },
                    { 335, "Dwarf Hotot", 3 },
                    { 336, "Dwarf Lop [UK]", 3 },
                    { 337, "Enderby Island", 3 },
                    { 338, "English Angora", 3 },
                    { 339, "English Lop", 3 },
                    { 340, "English Spot", 3 },
                    { 341, "Fauve de Bourgogne", 3 },
                    { 342, "Flemish Giant [UK]", 3 },
                    { 343, "Flemish Giant [US]", 3 },
                    { 344, "Florida White", 3 },
                    { 345, "Fox", 3 },
                    { 346, "Fox–Silver [UK]", 3 },
                    { 347, "French Angora", 3 },
                    { 348, "French Lop", 3 },
                    { 349, "Gabali", 3 },
                    { 350, "German Angora", 3 },
                    { 351, "German Lop", 3 },
                    { 352, "Giant Angora", 3 },
                    { 353, "Giant Chinchilla [US]", 3 },
                    { 354, "Giant Havana", 3 },
                    { 355, "Giant Marburger", 3 },
                    { 356, "Giant Papillon [UK]", 3 },
                    { 357, "Giant Silver", 3 },
                    { 358, "Giant Smoke Pearl", 3 },
                    { 359, "Giza White", 3 },
                    { 360, "Golden Glavcot", 3 },
                    { 361, "Gotland", 3 },
                    { 362, "Gouwenaar", 3 },
                    { 363, "Grey Pearl of Halle", 3 },
                    { 364, "Güzelçamlı", 3 },
                    { 365, "Harlequin [UK]", 3 },
                    { 366, "Harlequin [US]", 3 },
                    { 367, "Harlequin Rex", 3 },
                    { 368, "Havana [UK]", 3 },
                    { 369, "Havana [US]", 3 },
                    { 370, "Himalayan", 3 },
                    { 371, "Holland Lop [US]", 3 },
                    { 372, "Hulstlander", 3 },
                    { 373, "Hungarian Giant", 3 },
                    { 374, "Isabella", 3 },
                    { 375, "Jamora", 3 },
                    { 376, "Jersey Wooly", 3 },
                    { 377, "Kabyle", 3 },
                    { 378, "Lilac [UK]", 3 },
                    { 379, "Lilac [US]", 3 },
                    { 380, "Lionhead [UK]", 3 },
                    { 381, "Lionhead [US]", 3 },
                    { 382, "Liptov Baldspotted Rabbit", 3 },
                    { 383, "Lynx", 3 },
                    { 384, "Marburger Feh [UK]", 3 },
                    { 385, "Mecklenburger Piebald", 3 },
                    { 386, "Meissner Lop", 3 },
                    { 387, "Mellerud rabbit", 3 },
                    { 388, "Mini Lop [US]", 3 },
                    { 389, "Mini Rex", 3 },
                    { 390, "Mini Satin [US]", 3 },
                    { 391, "Miniature Cashmere Lop", 3 },
                    { 392, "Miniature Lion Lop", 3 },
                    { 393, "Miniature Lop [UK/NL]", 3 },
                    { 394, "Miniature Papillon", 3 },
                    { 395, "Miniature Satin [UK]", 3 },
                    { 396, "Moshtohor", 3 },
                    { 397, "Netherland Dwarf", 3 },
                    { 398, "New Zealand [US]", 3 },
                    { 399, "New Zealand red [UK]", 3 },
                    { 400, "New Zealand white [UK]", 3 },
                    { 401, "Nitransky", 3 },
                    { 402, "Opossum", 3 },
                    { 403, "Orange", 3 },
                    { 404, "Orylag", 3 },
                    { 405, "Ørestad", 3 },
                    { 406, "Palomino", 3 },
                    { 407, "Pannon White", 3 },
                    { 408, "Perlfee", 3 },
                    { 409, "Plush Lop (Miniature)", 3 },
                    { 410, "Plush Lop (Standard)", 3 },
                    { 411, "Pointed Beveren", 3 },
                    { 412, "Polish [UK]", 3 },
                    { 413, "Polish [US]", 3 },
                    { 414, "Rex [US]", 3 },
                    { 415, "Rhinelander", 3 },
                    { 416, "Rhone", 3 },
                    { 417, "SA Phendula", 3 },
                    { 418, "Sachsengold", 3 },
                    { 419, "Sallander", 3 },
                    { 420, "San Juan", 3 },
                    { 421, "Satin [UK]", 3 },
                    { 422, "Satin [US]", 3 },
                    { 423, "Satin Angora", 3 },
                    { 424, "Schwarzgrannen [UK]", 3 },
                    { 425, "Separator [DE]", 3 },
                    { 426, "Siamese Sable", 3 },
                    { 427, "Siberian", 3 },
                    { 428, "Silver [UK]", 3 },
                    { 429, "Silver [US]", 3 },
                    { 430, "Silver Fox [US]", 3 },
                    { 431, "Silver Marten", 3 },
                    { 432, "Simenwar", 3 },
                    { 433, "Slovenian Rabbit", 3 },
                    { 434, "Smoke Pearl", 3 },
                    { 435, "Spanish Giant", 3 },
                    { 436, "Squirrel", 3 },
                    { 437, "Standard Chinchilla [US]", 3 },
                    { 438, "Stone rabbit", 3 },
                    { 439, "Sussex", 3 },
                    { 440, "Swedish Fur", 3 },
                    { 441, "Swiss Fox", 3 },
                    { 442, "Tadla", 3 },
                    { 443, "Tan", 3 },
                    { 444, "Tax-Xiber", 3 },
                    { 445, "Teddy Dwarf", 3 },
                    { 446, "Teddy Lop", 3 },
                    { 447, "Thrianta", 3 },
                    { 448, "Thuringer", 3 },
                    { 449, "Tri-Colour Dutch", 3 },
                    { 450, "Tri-Colour English", 3 },
                    { 451, "Trønder", 3 },
                    { 452, "V-line", 3 },
                    { 453, "Velveteen Lop", 3 },
                    { 454, "Vienna Coloured", 3 },
                    { 455, "Vienna White", 3 },
                    { 456, "Wheaten", 3 },
                    { 457, "Wheaten Lynx", 3 },
                    { 458, "White Country", 3 },
                    { 459, "Zemmouri", 3 },
                    { 460, "Zika", 3 },
                    { 461, "Other", 3 },
                    { 462, "African Grey Parrot", 4 },
                    { 463, "Alexandrine Parakeet", 4 },
                    { 464, "Amazon Parrot", 4 },
                    { 465, "Blue-and-Gold Macaw", 4 },
                    { 466, "Blue-Crowned Conure", 4 },
                    { 467, "Blue-Fronted Amazon", 4 },
                    { 468, "Blue-Headed Pionus", 4 },
                    { 469, "Bourke’s Parrot", 4 },
                    { 470, "Budgie (Parakeet)", 4 },
                    { 471, "Caique", 4 },
                    { 472, "Canary", 4 },
                    { 473, "Canary-Winged Parakeet", 4 },
                    { 474, "Cockatiel", 4 },
                    { 475, "Cockatoo", 4 },
                    { 476, "Conure", 4 },
                    { 477, "Crimson Rosella", 4 },
                    { 478, "Derbyan Parakeet", 4 },
                    { 479, "Diamond Dove", 4 },
                    { 480, "Double Yellow-Headed Amazon Parrot", 4 },
                    { 481, "Dove", 4 },
                    { 482, "Eclectus", 4 },
                    { 483, "Finch", 4 },
                    { 484, "Fischer’s Lovebird", 4 },
                    { 485, "Goffin’s Cockatoo", 4 },
                    { 486, "Golden-Mantled Rosella", 4 },
                    { 487, "Gouldian Finch", 4 },
                    { 488, "Green-Cheeked Conure", 4 },
                    { 489, "Green-Winged Macaw", 4 },
                    { 490, "Hahn’s Macaw", 4 },
                    { 491, "Hawk-Headed Parrot", 4 },
                    { 492, "Hyacinth Macaw", 4 },
                    { 493, "Indian Ring-Necked Parakeet", 4 },
                    { 494, "Jenday Conure", 4 },
                    { 495, "Lilac-Crowned Amazon", 4 },
                    { 496, "Lineolated Parakeet", 4 },
                    { 497, "Lory", 4 },
                    { 498, "Lovebird", 4 },
                    { 499, "Macaw", 4 },
                    { 500, "Meyer’s Parrot", 4 },
                    { 501, "Moluccan Cockatoo", 4 },
                    { 502, "Orange-Winged Amazon Parrot", 4 },
                    { 503, "Owl Finch", 4 },
                    { 504, "Pacific Parrotlet", 4 },
                    { 505, "Parrot", 4 },
                    { 506, "Parrotlet", 4 },
                    { 507, "Peach-Faced Lovebird", 4 },
                    { 508, "Pionus Parrot", 4 },
                    { 509, "Poicephalus", 4 },
                    { 510, "Psittacula", 4 },
                    { 511, "Quaker Parakeet", 4 },
                    { 512, "Rainbow Lory", 4 },
                    { 513, "Red Lory", 4 },
                    { 514, "Red-Factor Canary", 4 },
                    { 515, "Ring-Necked Dove", 4 },
                    { 516, "Rosella", 4 },
                    { 517, "Scarlet Macaw", 4 },
                    { 518, "Scarlet-Chested Parakeet", 4 },
                    { 519, "Senegal Parrot", 4 },
                    { 520, "Severe Macaw", 4 },
                    { 521, "Society Finch", 4 },
                    { 522, "Song Canary", 4 },
                    { 523, "Sun Conure", 4 },
                    { 524, "Umbrella Cockatoo", 4 },
                    { 525, "Vasa Parrot", 4 },
                    { 526, "White-Capped Pionus", 4 },
                    { 527, "Yellow-Collared Macaw", 4 },
                    { 528, "Yellow-Naped Amazon Parrot", 4 },
                    { 529, "Zebra Finch", 4 },
                    { 530, "Other", 4 },
                    { 531, "American Guinea Pig", 5 },
                    { 532, "Crested Guinea Pig", 5 },
                    { 533, "Teddy Guinea Pig", 5 },
                    { 534, "Rex Guinea Pig", 5 },
                    { 535, "Abyssinian Guinea Pig", 5 },
                    { 536, "Cuy", 5 },
                    { 537, "Peruvian Guinea Pig", 5 },
                    { 538, "Coronet Guinea Pig", 5 },
                    { 539, "Silkie Guinea Pig", 5 },
                    { 540, "Merino Guinea Pig", 5 },
                    { 541, "Texel Guinea Pig", 5 },
                    { 542, "Lunkarya Guinea Pig", 5 },
                    { 543, "Skinny Guinea Pig", 5 },
                    { 544, "Baldwin Guinea Pig", 5 },
                    { 545, "Other", 5 },
                    { 546, "Syrian Hamster ", 6 },
                    { 547, "European Hamster", 6 },
                    { 548, "Roborovski (aka Robo) Dwarf Hamster", 6 },
                    { 549, "Chinese Hamster", 6 },
                    { 550, "Winter White Dwarf (Djungarian) Hamster", 6 },
                    { 551, "Campbell’s Dwarf Hamster", 6 },
                    { 552, "Turkish Hamster", 6 },
                    { 553, "Other", 6 },
                    { 554, "Domestic Ferret", 7 },
                    { 555, "Other", 7 },
                    { 556, "Mixed Breed", 8 },
                    { 557, "Other", 8 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_pet_breeds_SpeciesId",
                schema: "shelter_hub",
                table: "pet_breeds",
                column: "SpeciesId");

            migrationBuilder.CreateIndex(
                name: "IX_pets_BreedId",
                schema: "shelter_hub",
                table: "pets",
                column: "BreedId");

            migrationBuilder.CreateIndex(
                name: "IX_pets_ShelterId",
                schema: "shelter_hub",
                table: "pets",
                column: "ShelterId");

            migrationBuilder.CreateIndex(
                name: "IX_pets_SpeciesId",
                schema: "shelter_hub",
                table: "pets",
                column: "SpeciesId");

            migrationBuilder.CreateIndex(
                name: "IX_pets_Status",
                schema: "shelter_hub",
                table: "pets",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_pets_Status_SpeciesId_BreedId",
                schema: "shelter_hub",
                table: "pets",
                columns: new[] { "Status", "SpeciesId", "BreedId" });

            migrationBuilder.CreateIndex(
                name: "IX_shelters_Location",
                schema: "shelter_hub",
                table: "shelters",
                column: "Location")
                .Annotation("Npgsql:IndexMethod", "gist");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "pets",
                schema: "shelter_hub");

            migrationBuilder.DropTable(
                name: "pet_breeds",
                schema: "shelter_hub");

            migrationBuilder.DropTable(
                name: "shelters",
                schema: "shelter_hub");

            migrationBuilder.DropTable(
                name: "pet_species",
                schema: "shelter_hub");
        }
    }
}
