// <auto-generated />
using Longhl104.ShelterHub;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Longhl104.ShelterHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shelter_hub")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Longhl104.ShelterHub.Models.PostgreSql.Shelter", b =>
                {
                    b.Property<int>("ShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShelterId"));

                    b.Property<string>("ShelterAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShelterContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShelterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShelterId");

                    b.ToTable("shelters", "shelter_hub");
                });
#pragma warning restore 612, 618
        }
    }
}
